[target.x86_64-unknown-linux-gnu]
xargo = false

[target.aarch64-unknown-linux-gnu]
xargo = false

[target.x86_64-pc-windows-msvc]
xargo = false

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
] 